############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Consortium Partners"
url = "consortium/"
weight = 2

[[main]]
name = "Project Description"
url = "about/"
weight = 2

[[main]]
name = "Publications"
url = "publications/"
weight = 3

[[main]]
name = "Dissemination"
url = "dissemination/"
weight = 4

# [[main]]
# name = "Blog"
# url = "blog/"
# weight = 2

# [[main]]
# name = "Elements"
# url = "elements/"
# weight = 3

# [[main]]
# weight = 4
# name = "Pages"
# hasChildren = true


# [[main]]
# parent = "Pages"
# name = "Categories"
# url = "categories/"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "404/"


# # footer menu
# [[footer]]
# name = "About"
# url = "about/"
# weight = 1

# [[footer]]
# name = "Elements"
# url = "elements/"
# weight = 2

# [[footer]]
# name = "Privacy Policy"
# url = "privacy-policy/"
# weight = 3
